baseURL = 'https://hyouteki.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
paginate = 5
theme = "hugo-theme-terminal"
enableemoji = true

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "projects"
  themeColor = "green"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = true
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  updatedDatePrefix = "Last update"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "mainlakshayhoon"
  site = "https://hyouteki.github.io/"

[languages]
  [languages.en]
    languageName = "English"
    title = "Hyouteki"
    subtitle = ""
    owner = "hyouteki"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Hyouteki"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blogs"
        name = "Blogs"
        url = "/blogs"
        weight=3

      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
        weight=4

      [[languages.en.menu.main]]
        identifier = "writings"
        name = "Writings"
        url = "/writings"
        weight=5

      [[languages.en.menu.main]]
        identifier = "tags"
        name = "All tags"
        url = "/tags"
        weight=6

      [[languages.en.menu.main]]
        identifier = "resume"
        name = "RESUME"
        url = "https://github.com/Hyouteki/me/raw/main/assets/CV.pdf"
        weight=7

      [[languages.en.menu.main]]
        identifier = "license"
        name = "LICENSE"
        url = "/license"
        weight=8