name = "Duckquill"
description = "Modern, pretty, and clean theme"
license = "MIT"
homepage = "https://codeberg.org/daudix/duckquill"
min_version = "0.17.2"
demo = "https://daudix.codeberg.page/duckquill"

[extra]

[author]
name = "David Lapshin"
homepage = "https://daudix.codeberg.page"
